/**
 * @file demo_impl.c
 *
 * MIT License
 *
 * Copyright (c) 2022 PRO1 IAQ, INC.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

/**
 * @brief Autogenerated by jrpc_gen.py from demo_defs.h -- do not edit.
 */

// *****************************************************************************
// Includes

#include "demo_impl.h"

#include "demo_bsp.h"
#include "light_sensor.h"
#include "user_button.h"

#include "jems.h"
#include "jrpc.h"
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>

// *****************************************************************************
// Private types and definitions

#define MAX_JSON_DEPTH 10

// *****************************************************************************
// Private (static) storage

static jems_t s_jems;

static jems_level_t s_jems_levels[MAX_JSON_DEPTH];

// *****************************************************************************
// Private (static, forward) declarations

// *****************************************************************************
// Public code

void demo_init(void) {
  jems_init(&s_jems, s_jems_levels, MAX_JSON_DEPTH, demo_bsp_putc);
}

void demo_decode(const char *json, size_t json_len) {
  jrpc_t *jrpc = jrpc_parse(jrpc_instance(), json, json_len);

  if (!jrpc_is_rpc(jrpc)) {
    printf("WARN: could not parse as an RPC: %.*s\n", json_len, json);
  } else if (user_button_decode(jrpc)) {
  } else if (light_sensor_decode(jrpc)) {
  } else {
    printf("WARN: could not decode %.*s\n", json_len, json);
  }
}

jems_t *demo_jems_instance(void) {
  return &s_jems;
}

// *****************************************************************************
// Private (static) code

// *****************************************************************************
// End of file
